[package]
name = "antelope"
version = "0.0.4"
authors = ["Denis Carriere <denis@pinax.network>"]
description = "Antelope Standard Library"
homepage = "https://github.com/pinax-network/antelope-rust"
repository = "https://github.com/pinax-network/antelope-rust"
categories = [ "api-bindings", "cryptography::cryptocurrencies", "data-structures", "parsing", "value-formatting"]
keywords = ["antelope", "blockchain", "crypto"]
readme = "README.md"
license = "MIT OR Apache-2.0"
edition = "2021"

[badges]
maintenance = { status = "actively-developed" }
