name: "🛠 Add Type"
description: Create a new ticket for a new type.
title: "🛠 [TYPE] - <title>"
labels: [
  "type"
]
body:
  - type: input
    id: reference-url
    attributes:
      label: "Reference URL"
      description: Please enter your GitHub URL to provide a code reference of type
      placeholder: ex. https://github.com/AntelopeIO/cdt/blob/main/libraries/eosiolib/core/eosio
    validations:
      required: true
  - type: textarea
    id: constructors
    attributes:
      label: "Custom Antelope Types"
      description: Please enter the list of constructors to be supported
      value: |
        - [ ] new()
        - [ ] default()
        - [ ] from()
    validations:
      required: true

  - type: textarea
    id: constructors
    attributes:
      label: "Custom Antelope Methods"
      description: Please enter the list of custom methods to be supported
      value: |
        - [ ] length()
        - [ ] is_valid()
        - [ ] raw()
        - [ ] to_string()
    validations:
      required: true

  - type: textarea
    id: common
    attributes:
      label: "Common Rust Traits"
      description: Please enter the list of common Rust traits to be supported
      value: |
        - [ ] `AsRef`
        - [ ] `AsBool`
        - [ ] `Copy`
        - [ ] `Clone`
        - [ ] `Display`
          - [ ] `From<u64>`
          - [ ] `From<&str>`
    validations:
      required: true

  - type: textarea
    id: operators
    attributes:
      label: "Operators"
      description: Please enter the list of [operators](https://doc.rust-lang.org/book/appendix-02-operators.html) types to be supported
      value: |
        - `PartialEq`
          - [ ] expr != expr
          - [ ] expr == expr
        - `PartialOrd` (`partial_cmp` & `cmp`)
          - [ ] expr < expr
          - [ ] expr > expr
          - [ ] expr <= expr
          - [ ] expr >= expr
        - `Neg`
          - [ ] - expr
        - `Sub`
          - [ ] expr - expr
        - `SubAssign`
          - [ ] var -= expr
        - `Add`
          - [ ] expr + expr
        - `AddAssign`
          - [ ] var += expr
        - `Mul`
          - [ ] expr * expr
        - `MulAssign`
          - [ ] var *= expr
        - `Div`
          - [ ] expr / expr
        - `DivAssign`
          - [ ] var /= expr
    validations:
      required: true

