name: Minimal CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: cargo check
    - run: cargo test
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
    
    
